apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cockpit-data
  namespace: cockpit
  labels:
    app.kubernetes.io/part-of: cockpit
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
